@Library('mylib')_

pipeline
{
    agent any
    stages
    {
        stage('contDown')
        {
            steps
            {
                script
                {
                    cicd.newDownload("maven.git")
                }
            }
        }
        stage('contBuild')
        {
            steps
            {
                script
                {
                    cicd.newBuild()
                }
            }
        }
        stage('contdeploy')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("sharedlibrarydec1","172.13.1.31","test")
                }
            }
        }
        stage('contTesting')
        {
            steps
            {
                script
                {
                    cicd.newDownload("maven-testing.git")
                    cicd.runSelenium("sharedlibrarydec1")
                }
            }
        }
        stage('contDelivery')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("sharedlibrarydec1","172.13.1.109","prod")
                }
            }
        }
    }
    
}
